name: publish to nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.405
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
       PROJECT_FILE_PATH: FondyCoreSDK/FondyCoreSDK.csproj
       VERSION_FILE_PATH: FondyCoreSDK/FondyCoreSDK.nuspec
       VERSION_REGEX: ^\s*<version>(.*)<\/version>\s*$
       TAG_FORMAT: '*'
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 